"""Mass-gathering stress-test mode (Section 5.6): analysis side.

Sweeps simulated EV density in a zone and reports where the recommendation
and grid systems break down - which zones fail, at what density, and how
much additional charging capacity the what-if mode (Section 4.6) would
need to recommend to keep wait times under a threshold. The live density
spike itself is generated by `simulation/event_stress_sim.py`; this module
is the capacity-planning report generator, independently testable.
"""
from __future__ import annotations

import math
from dataclasses import dataclass


@dataclass
class DensityLevelResult:
    density_multiplier: float
    vehicle_count: int
    simultaneous_load_kw: float
    is_overloaded: bool


@dataclass
class StressTestReport:
    feeder_id: str
    results: list[DensityLevelResult]
    breaking_point_multiplier: float | None
    additional_capacity_needed_kw: float


def _simultaneous_load_kw(vehicle_count: int, avg_charger_power_kw: float, simultaneous_charge_fraction: float) -> float:
    return vehicle_count * simultaneous_charge_fraction * avg_charger_power_kw


def sweep_density(feeder_id: str, feeder_capacity_kw: float, baseline_vehicle_count: int,
                   avg_charger_power_kw: float, simultaneous_charge_fraction: float,
                   density_multipliers: list[float]) -> StressTestReport:
    results = []
    breaking_point = None
    for multiplier in density_multipliers:
        vehicle_count = math.ceil(baseline_vehicle_count * multiplier)
        load_kw = _simultaneous_load_kw(vehicle_count, avg_charger_power_kw, simultaneous_charge_fraction)
        is_overloaded = load_kw > feeder_capacity_kw
        results.append(DensityLevelResult(multiplier, vehicle_count, round(load_kw, 2), is_overloaded))
        if is_overloaded and breaking_point is None:
            breaking_point = multiplier

    peak_load_kw = max((r.simultaneous_load_kw for r in results), default=0.0)
    additional_capacity_needed_kw = max(0.0, peak_load_kw - feeder_capacity_kw)

    return StressTestReport(
        feeder_id=feeder_id,
        results=results,
        breaking_point_multiplier=breaking_point,
        additional_capacity_needed_kw=round(additional_capacity_needed_kw, 2),
    )


def recommend_additional_stations(additional_capacity_needed_kw: float, station_capacity_kw: float) -> int:
    if additional_capacity_needed_kw <= 0:
        return 0
    return math.ceil(additional_capacity_needed_kw / station_capacity_kw)
